# Generated by Django 4.0.5 on 2022-06-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='date_posted',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
    ]
