# Generated by Django 4.0.5 on 2022-06-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_alter_comment_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
    ]
